[package]
name = "nazgul"
description = "A library that implements various ring signature schemes"
readme = "README.md"
license = "MIT"
version = "2.1.0"
authors = ["Edwin Jose Palathinkal <edwinhere@gmail.com>"]
edition = "2018"
keywords = ["cryptography", "crypto", "ristretto", "ristretto255", "monero"]
categories = ["no-std", "cryptography::cryptocurrencies", "cryptography", "wasm"]
repository = "https://github.com/edwinhere/nazgul"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", default-features = false }
bs58 = "0.5"
curve25519-dalek = { version = "4", default-features = false }
digest = { version = "^0.10", default-features = false }
rand_core = { version = "^0.6.4", default-features = false, features = ["getrandom"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
wasm-bindgen = { version = "0.2.104", optional = true }
rand = { version = "^0.8", default-features = false, features = ["getrandom"], optional = true }
sha3 = "^0.10"
cpu-time = "1.0.0"

[dev-dependencies]
sha2 = { version = "^0.10", default-features = false }
sha3 = { version = "^0.10", default-features = false }
blake2 = { version = "^0.10", default-features = false }
rand = { version = "^0.8", default-features = false, features = ["getrandom"] }
serde_json = "1.0"
criterion = "0.5"
rand_chacha = "0.3"

[features]
default = ["std", "serde-derive"]
serde-derive = ["serde", "curve25519-dalek/serde", "no_std"]
std = [
    "digest/std",
    "rand_core/std",
    "curve25519-dalek/alloc",
    "curve25519-dalek/zeroize",
    "curve25519-dalek/precomputed-tables",
    "curve25519-dalek/rand_core",
    "curve25519-dalek/digest",
    "sha2/std",
    "sha3/std",
    "blake2/std",
    "rand/std"
]
no_std = [
    "curve25519-dalek/alloc",
    "curve25519-dalek/zeroize",
    "curve25519-dalek/rand_core",
    "curve25519-dalek/digest",
    "rand_core/alloc",
    "digest/alloc"
]
wasm = ["wasm-bindgen", "std", "rand"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[[test]]
name = "no_std_tests"
path = "tests/no_std_tests.rs"
required-features = ["no_std"]

[[bench]]
name = "blsag_benches"
harness = false
required-features = ["std"]

[[bin]]
name = "time_model"
path = "src/bin/time_model.rs"
required-features = ["std"]
